# Generated by Django 6.0.1 on 2026-01-20 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0002_userteam_league"),
    ]

    operations = [
        migrations.AddField(
            model_name="userteam",
            name="budget",
            field=models.DecimalField(decimal_places=1, default=100.0, max_digits=6),
        ),
    ]
