# Generated by Django 6.0.1 on 2026-01-20 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0003_userteam_budget"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userteam",
            name="budget",
        ),
    ]
