# Generated by Django 6.0.1 on 2026-01-20 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leagues", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="league",
            name="league_type",
            field=models.CharField(
                choices=[
                    ("year_group", "Year Group"),
                    ("whole_school", "Whole School"),
                    ("class", "Class"),
                    ("other", "Other"),
                ],
                default="class",
                help_text="Type of league",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="league",
            name="year_group",
            field=models.CharField(
                blank=True,
                choices=[
                    ("7", "Year 7"),
                    ("8", "Year 8"),
                    ("9", "Year 9"),
                    ("10", "Year 10"),
                    ("11", "Year 11"),
                    ("12", "Year 12"),
                    ("13", "Year 13"),
                ],
                help_text="For year group leagues",
                max_length=2,
                null=True,
            ),
        ),
    ]
