# Generated by Django 6.0.1 on 2026-01-19 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fpl_id", models.IntegerField(unique=True)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("web_name", models.CharField(max_length=100)),
                (
                    "position",
                    models.IntegerField(
                        choices=[(1, "GK"), (2, "DEF"), (3, "MID"), (4, "FWD")]
                    ),
                ),
                (
                    "now_cost",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                ("total_points", models.IntegerField(default=0)),
                ("minutes", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["-total_points"],
            },
        ),
    ]
