# Generated by Django 6.0.1 on 2026-01-20 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="gameweek_scores",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
